package com.science.gtnl.common.recipe;

import static com.science.gtnl.Mods.ScienceNotLeisure;
import static gregtech.api.enums.Mods.*;
import static gregtech.api.util.GTModHandler.getModItem;

import java.util.Arrays;
import java.util.List;

import com.science.gtnl.common.GTNLItemList;
import com.science.gtnl.loader.IScriptLoader;

import fox.spiteful.avaritia.crafting.ExtremeCraftingManager;

public class ScriptAvaritia implements IScriptLoader {

    @Override
    public String getScriptName() {
        return "Avaritia";
    }

    @Override
    public List<String> getDependencies() {
        return Arrays.asList(
            AppliedEnergistics2.ID,
            EnderIO.ID,
            SGCraft.ID,
            TecTech.ID,
            AE2FluidCraft.ID,
            GregTech.ID,
            NewHorizonsCoreMod.ID,
            ScienceNotLeisure.ID);
    }

    @Override
    public void loadRecipes() {
        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier0", 1, 0, missing),
                "AAAABAAAA",
                "ACDEFGHIA",
                "AJKLKLKMA",
                "ANLOPQLRA",
                "STKUVWKXY",
                "AZL012L3A",
                "A4KL5LK6A",
                "A789abcdA",
                "AAAAeAAAA",
                'A',
                getModItem(NewHorizonsCoreMod.ID, "item.StargateShieldingFoil", 1, 0, missing),
                'B',
                getModItem(NewHorizonsCoreMod.ID, "item.DimensionalGatePlate", 1, 0, missing),
                'C',
                getModItem(SGCraft.ID, "sgCoreCrystal", 1, 0, missing),
                'D',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:molten.eternity,Amount:114514}}",
                    missing),
                'E',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15410, missing),
                'F',
                getModItem(NewHorizonsCoreMod.ID, "item.DimensionalChevron", 1, 0, missing),
                'G',
                getModItem(TecTech.ID, "item.tm.itemAstralArrayFabricator", 1, 0, missing),
                'H',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:molten.magmatter,Amount:114514}}",
                    missing),
                'I',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32177, missing),
                'J',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:molten.universium,Amount:114514}}",
                    missing),
                'K',
                getModItem(SGCraft.ID, "stargateRing", 1, 1, missing),
                'L',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'M',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:quarkgluonplasma,Amount:114514}}",
                    missing),
                'N',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15411, missing),
                'O',
                getModItem(NewHorizonsCoreMod.ID, "item.PolychromeFramePart", 1, 0, missing),
                'P',
                getModItem(SGCraft.ID, "sgChevronUpgrade", 1, 0, missing),
                'Q',
                getModItem(NewHorizonsCoreMod.ID, "item.DimensionalFramePart", 1, 0, missing),
                'R',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32028, missing),
                'S',
                getModItem(NewHorizonsCoreMod.ID, "item.OriginGatePlate", 1, 0, missing),
                'T',
                getModItem(NewHorizonsCoreMod.ID, "item.OriginChevron", 1, 0, missing),
                'U',
                getModItem(SGCraft.ID, "rfPowerUnit", 1, 0, missing),
                'V',
                getModItem(NewHorizonsCoreMod.ID, "item.StargateCrystalAncients", 1, 0, missing),
                'W',
                getModItem(SGCraft.ID, "stargateController", 1, 0, missing),
                'X',
                getModItem(NewHorizonsCoreMod.ID, "item.HarmonicChevron", 1, 0, missing),
                'Y',
                getModItem(NewHorizonsCoreMod.ID, "item.HarmonicGatePlate", 1, 0, missing),
                'Z',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4143, missing),
                '0',
                getModItem(NewHorizonsCoreMod.ID, "item.HarmonicFramePart", 1, 0, missing),
                '1',
                getModItem(SGCraft.ID, "sgIrisUpgrade", 1, 0, missing),
                '2',
                getModItem(NewHorizonsCoreMod.ID, "item.OriginFramePart", 1, 0, missing),
                '3',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32027, missing),
                '4',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:sgcrystalslurry,Amount:114514}}",
                    missing),
                '5',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                '6',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:molten.magnetohydrodynamicallyconstrainedstarmatter,Amount:114514}}",
                    missing),
                '7',
                GTNLItemList.CircuitResonaticULV.get(1),
                '8',
                getModItem(AppliedEnergistics2.ID, "item.ItemExtremeStorageCell.Universe", 1, 0, missing),
                '9',
                getModItem(AppliedEnergistics2.ID, "tile.BlockCreativeEnergyCell", 1, 0, missing),
                'a',
                getModItem(NewHorizonsCoreMod.ID, "item.PolychromeChevron", 1, 0, missing),
                'b',
                getModItem(EnderIO.ID, "blockCapBank", 1, 0, missing),
                'c',
                getModItem(AE2FluidCraft.ID, "fluid_storage.Universe", 1, 0, missing),
                'd',
                getModItem(SGCraft.ID, "sgControllerCrystal", 1, 0, missing),
                'e',
                getModItem(NewHorizonsCoreMod.ID, "item.PolychromeGatePlate", 1, 0, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier1", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOLPQ",
                "RLyTyTyLU",
                "VWTXYZT01",
                "23y456y78",
                "9aTbcdTef",
                "gLyTSTyLh",
                "ijLklmLno",
                "pqrstuvwx",
                'A',
                getModItem(GalacticraftCore.ID, "item.spaceship", 1, 0, missing),
                'B',
                getModItem(GalacticraftMars.ID, "item.spaceshipTier2", 1, 0, missing),
                'C',
                getModItem(GalacticraftMars.ID, "item.itemTier3Rocket", 1, 0, missing),
                'D',
                getModItem(GalaxySpace.ID, "item.Tier4Rocket", 1, 0, missing),
                'E',
                getModItem(ElectroMagicTools.ID, "EMTSolars4", 1, 14, missing),
                'F',
                getModItem(GalaxySpace.ID, "item.Tier5Rocket", 1, 0, missing),
                'G',
                getModItem(GalaxySpace.ID, "item.Tier6Rocket", 1, 0, missing),
                'H',
                getModItem(GalaxySpace.ID, "item.Tier7Rocket", 1, 0, missing),
                'I',
                getModItem(GalaxySpace.ID, "item.Tier8Rocket", 1, 0, missing),
                'J',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 865, missing),
                'K',
                getModItem(Avaritia.ID, "Cosmic_Meatballs", 1, 0, missing),
                'L',
                getModItem(Avaritia.ID, "Resource", 1, 8, missing),
                'M',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade3purifiedwater,Amount:2147483647}}",
                    missing),
                'N',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallyshiftedsuperfluid,Amount:114514}}",
                    missing),
                'O',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade4purifiedwater,Amount:2147483647}}",
                    missing),
                'P',
                getModItem(Avaritia.ID, "Ultimate_Stew", 1, 0, missing),
                'Q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31074, missing),
                'R',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31073, missing),
                'S',
                getModItem(ScienceNotLeisure.ID, "StargateTier0", 1, 0, missing),
                'T',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'U',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31079, missing),
                'V',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 866, missing),
                'W',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade2purifiedwater,Amount:2147483647}}",
                    missing),
                'X',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9402, missing),
                'Y',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9403, missing),
                'Z',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9404, missing),
                '0',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade2purifiedwater,Amount:2147483647}}",
                    missing),
                '1',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31076, missing),
                '2',
                getModItem(ElectroMagicTools.ID, "EMTSolars4", 1, 15, missing),
                '3',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:molten.sixphasedcopper,Amount:114514}}",
                    missing),
                '4',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9405, missing),
                '5',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9406, missing),
                '6',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9408, missing),
                '7',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:phononmedium,Amount:114514}}",
                    missing),
                '8',
                getModItem(ElectroMagicTools.ID, "EMTSolars5", 1, 2, missing),
                '9',
                getModItem(NewHorizonsCoreMod.ID, "item.PolychromeQuantumCircuit", 1, 0, missing),
                'a',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade1purifiedwater,Amount:2147483647}}",
                    missing),
                'b',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9409, missing),
                'c',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9412, missing),
                'd',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9414, missing),
                'e',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade6purifiedwater,Amount:2147483647}}",
                    missing),
                'f',
                getModItem(NewHorizonsCoreMod.ID, "item.PolychromePikoCircuit", 1, 0, missing),
                'g',
                getModItem(NewHorizonsCoreMod.ID, "item.DimensionalQuantumCircuit", 1, 0, missing),
                'h',
                getModItem(NewHorizonsCoreMod.ID, "item.DimensionalPikoCircuit", 1, 0, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32758, missing),
                'j',
                getModItem(Avaritia.ID, "Akashic_Record", 1, 0, missing),
                'k',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade8purifiedwater,Amount:2147483647}}",
                    missing),
                'l',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:antimatter,Amount:114514}}",
                    missing),
                'm',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:grade7purifiedwater,Amount:2147483647}}",
                    missing),
                'n',
                getModItem(Avaritia.ID, "Orb_Armok", 1, 0, missing),
                'o',
                getModItem(NewHorizonsCoreMod.ID, "item.OriginNanoCircuit", 1, 0, missing),
                'p',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 358, missing),
                'q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3008, missing),
                'r',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 687, missing),
                's',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3004, missing),
                't',
                getModItem(ElectroMagicTools.ID, "EMTSolars5", 1, 1, missing),
                'u',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 686, missing),
                'v',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 2730, missing),
                'w',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 366, missing),
                'x',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3010, missing),
                'y',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier2", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "ST~V~V~WX",
                "YZV012V34",
                "56~789~ab",
                "cdVefgVhi",
                "jk~VUV~lm",
                "nopqrstuv",
                "wxyz/;:[]",
                'A',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.lead,Amount:114514}}",
                    missing),
                'B',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentresidue,Amount:114514}}",
                    missing),
                'C',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.plutonium241,Amount:114514}}",
                    missing),
                'D',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.americium,Amount:114514}}",
                    missing),
                'E',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.neon,Amount:114514}}",
                    missing),
                'F',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.germanium,Amount:114514}}",
                    missing),
                'G',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.krypton,Amount:114514}}",
                    missing),
                'H',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.selenium,Amount:114514}}",
                    missing),
                'I',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.radon,Amount:114514}}",
                    missing),
                'J',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.hafnium,Amount:114514}}",
                    missing),
                'K',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.sulfur,Amount:114514}}",
                    missing),
                'L',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.oxygen,Amount:114514}}",
                    missing),
                'M',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.nitrogen,Amount:114514}}",
                    missing),
                'N',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.helium,Amount:114514}}",
                    missing),
                'O',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.thorium232,Amount:114514}}",
                    missing),
                'P',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.boron,Amount:114514}}",
                    missing),
                'Q',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.rhenium,Amount:114514}}",
                    missing),
                'R',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.bismuth,Amount:114514}}",
                    missing),
                'S',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.iodine,Amount:114514}}",
                    missing),
                'T',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.zirconium,Amount:114514}}",
                    missing),
                'U',
                getModItem(ScienceNotLeisure.ID, "StargateTier1", 1, 0, missing),
                'V',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'W',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.bromine,Amount:114514}}",
                    missing),
                'X',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.xenon,Amount:114514}}",
                    missing),
                'Y',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.hypogen,Amount:114514}}",
                    missing),
                'Z',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.advancednitinol,Amount:114514}}",
                    missing),
                '0',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.chromaticglass,Amount:114514}}",
                    missing),
                '1',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.astraltitanium,Amount:114514}}",
                    missing),
                '2',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.celestialtungsten,Amount:114514}}",
                    missing),
                '3',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.dragonblood,Amount:114514}}",
                    missing),
                '4',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.tin,Amount:114514}}",
                    missing),
                '5',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.thallium,Amount:114514}}",
                    missing),
                '6',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.calcium,Amount:114514}}",
                    missing),
                '7',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.titanium,Amount:114514}}",
                    missing),
                '8',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1006, missing),
                '9',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.fermium,Amount:114514}}",
                    missing),
                'a',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.ruthenium,Amount:114514}}",
                    missing),
                'b',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.silver,Amount:114514}}",
                    missing),
                'c',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.radium,Amount:114514}}",
                    missing),
                'd',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.plutonium238,Amount:114514}}",
                    missing),
                'e',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.runite,Amount:114514}}",
                    missing),
                'f',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:rawstarmatter,Amount:114514}}",
                    missing),
                'g',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.force,Amount:114514}}",
                    missing),
                'h',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.rhugnor,Amount:114514}}",
                    missing),
                'i',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.zinc,Amount:114514}}",
                    missing),
                'j',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.technetium,Amount:114514}}",
                    missing),
                'k',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.neptunium,Amount:114514}}",
                    missing),
                'l',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.californium,Amount:114514}}",
                    missing),
                'm',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.niobium,Amount:114514}}",
                    missing),
                'n',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.curium,Amount:114514}}",
                    missing),
                'o',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.protactinium,Amount:114514}}",
                    missing),
                'p',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:exciteddtrc,Amount:114514}}",
                    missing),
                'q',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:exciteddtsc,Amount:114514}}",
                    missing),
                'r',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:exciteddtec,Amount:114514}}",
                    missing),
                's',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:exciteddtpc,Amount:114514}}",
                    missing),
                't',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:exciteddtcc,Amount:114514}}",
                    missing),
                'u',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.rhodium,Amount:114514}}",
                    missing),
                'v',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.nickel,Amount:114514}}",
                    missing),
                'w',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.polonium,Amount:114514}}",
                    missing),
                'x',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentcrudecatalyst,Amount:114514}}",
                    missing),
                'y',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentexoticcatalyst,Amount:114514}}",
                    missing),
                'z',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.thorium,Amount:114514}}",
                    missing),
                '/',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:stablebaryonicmatter,Amount:114514}}",
                    missing),
                ';',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentstellarcatalyst,Amount:114514}}",
                    missing),
                ':',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentprosaiccatalyst,Amount:114514}}",
                    missing),
                '[',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:dimensionallytranscendentresplendentcatalyst,Amount:114514}}",
                    missing),
                ']',
                createItemStack(
                    AE2FluidCraft.ID,
                    "fluid_packet",
                    1,
                    0,
                    "{FluidStack:{FluidName:plasma.iron,Amount:114514}}",
                    missing),
                '~',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier3", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "ST~V~V~WX",
                "YZV012V34",
                "56~789~ab",
                "cdVefgVhi",
                "jk~VUV~lm",
                "nopqrstuv",
                "wxyz/;:[]",
                'A',
                getModItem(GTNHLanthanides.ID, "item.photomask.uhpic", 1, 0, missing),
                'B',
                getModItem(GTNHLanthanides.ID, "item.photomask.npic", 1, 0, missing),
                'C',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 0, missing),
                'D',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 19, missing),
                'E',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 21, missing),
                'F',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 17, missing),
                'G',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 23, missing),
                'H',
                getModItem(GTNHLanthanides.ID, "item.photomask.ulpic", 1, 0, missing),
                'I',
                getModItem(GTNHLanthanides.ID, "item.photomask.qpic", 1, 0, missing),
                'J',
                getModItem(GTNHLanthanides.ID, "item.photomask.hpic", 1, 0, missing),
                'K',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15415, missing),
                'L',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 1, missing),
                'M',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 2, missing),
                'N',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6147, missing),
                'O',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 3, missing),
                'P',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 4, missing),
                'Q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15414, missing),
                'R',
                getModItem(GTNHLanthanides.ID, "item.photomask.lpic", 1, 0, missing),
                'S',
                getModItem(GTNHLanthanides.ID, "item.photomask.ppic", 1, 0, missing),
                'T',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 22, missing),
                'U',
                getModItem(ScienceNotLeisure.ID, "StargateTier2", 1, 0, missing),
                'V',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'W',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 5, missing),
                'X',
                getModItem(GTNHLanthanides.ID, "item.photomask.pic", 1, 0, missing),
                'Y',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32235, missing),
                'Z',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 9, missing),
                '0',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6581, missing),
                '1',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6588, missing),
                '2',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6149, missing),
                '3',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 6, missing),
                '4',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32238, missing),
                '5',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32240, missing),
                '6',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6586, missing),
                '7',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6139, missing),
                '8',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6154, missing),
                '9',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6143, missing),
                'a',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6585, missing),
                'b',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32237, missing),
                'c',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32239, missing),
                'd',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 10, missing),
                'e',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6583, missing),
                'f',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6397, missing),
                'g',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6141, missing),
                'h',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 15, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32236, missing),
                'j',
                getModItem(GTNHLanthanides.ID, "item.photomask.qbit", 1, 0, missing),
                'k',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 18, missing),
                'l',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 16, missing),
                'm',
                getModItem(GTNHLanthanides.ID, "item.photomask.nand", 1, 0, missing),
                'n',
                getModItem(GTNHLanthanides.ID, "item.photomask.ncpu", 1, 0, missing),
                'o',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15412, missing),
                'p',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 8, missing),
                'q',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 7, missing),
                'r',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 6982, missing),
                's',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 11, missing),
                't',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 20, missing),
                'u',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15413, missing),
                'v',
                getModItem(GTNHLanthanides.ID, "item.photomask.nor", 1, 0, missing),
                'w',
                getModItem(GTNHLanthanides.ID, "item.photomask.ssoc", 1, 0, missing),
                'x',
                getModItem(GTNHLanthanides.ID, "item.photomask.soc", 1, 0, missing),
                'y',
                getModItem(GTNHLanthanides.ID, "item.photomask.asoc", 1, 0, missing),
                'z',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 12, missing),
                '/',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 14, missing),
                ';',
                getModItem(GTPlusPlus.ID, "particleBase", 1, 13, missing),
                ':',
                getModItem(GTNHLanthanides.ID, "item.photomask.ram", 1, 0, missing),
                '[',
                getModItem(GTNHLanthanides.ID, "item.photomask.ilc", 1, 0, missing),
                ']',
                getModItem(GTNHLanthanides.ID, "item.photomask.cpu", 1, 0, missing),
                '~',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier4", 1, 0, missing),
                "ABCDEFGHI",
                "JKKLMNOOP",
                "QRSTSTSUV",
                "WRTXYZTU0",
                "12S345S67",
                "82T9abT6c",
                "d2STeTS6f",
                "ghhhijjjk",
                "lmmminnno",
                'A',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 14, missing),
                'B',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 0, missing),
                'C',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 3, missing),
                'D',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 1, missing),
                'E',
                getModItem(GTPlusPlus.ID, "item.BasicAgrichemItem", 1, 14, missing),
                'F',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 6, missing),
                'G',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 2, missing),
                'H',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 4, missing),
                'I',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 13, missing),
                'J',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 15, missing),
                'K',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4035, missing),
                'L',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4032, missing),
                'M',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4010, missing),
                'N',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4811, missing),
                'O',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4054, missing),
                'P',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 31, missing),
                'Q',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 19, missing),
                'R',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4086, missing),
                'S',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                'T',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'U',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4129, missing),
                'V',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 24, missing),
                'W',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 20, missing),
                'X',
                getModItem(GTPlusPlus.ID, "MU-metaitem.01", 1, 32105, missing),
                'Y',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 5, missing),
                'Z',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32428, missing),
                '0',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 26, missing),
                '1',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 21, missing),
                '2',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4581, missing),
                '3',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32429, missing),
                '4',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32416, missing),
                '5',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 8150, missing),
                '6',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4147, missing),
                '7',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 27, missing),
                '8',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 16, missing),
                '9',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32757, missing),
                'a',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 17, missing),
                'b',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32427, missing),
                'c',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 33, missing),
                'd',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 25, missing),
                'e',
                getModItem(ScienceNotLeisure.ID, "StargateTier3", 1, 0, missing),
                'f',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 32, missing),
                'g',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 23, missing),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4585, missing),
                'i',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4141, missing),
                'j',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4586, missing),
                'k',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 28, missing),
                'l',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 22, missing),
                'm',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4139, missing),
                'n',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 4143, missing),
                'o',
                getModItem(GTPlusPlus.ID, "item.BasicGenericChemItem", 1, 18, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier5", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "STUVWXYZ0",
                "123444567",
                "89a4b4cde",
                "fgh4i4jkl",
                "mnopqrstu",
                "vwxyz/<>;",
                ":[]^_=?~!",
                'A',
                getModItem(Avaritia.ID, "Singularity", 1, 4, missing),
                'B',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 5, missing),
                'C',
                getModItem(Avaritia.ID, "Singularity", 1, 8, missing),
                'D',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 0, missing),
                'E',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 17, missing),
                'F',
                getModItem(UniversalSingularities.ID, "universal.extraUtilities.singularity", 1, 0, missing),
                'G',
                getModItem(Avaritia.ID, "Singularity", 1, 0, missing),
                'H',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 18, missing),
                'I',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 11, missing),
                'J',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 2, missing),
                'K',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 1, missing),
                'L',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 2, missing),
                'M',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 0, missing),
                'N',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 5, missing),
                'O',
                getModItem(Avaritia.ID, "Singularity", 1, 1, missing),
                'P',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 4, missing),
                'Q',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 16, missing),
                'R',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 1, missing),
                'S',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 20, missing),
                'T',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 7, missing),
                'U',
                getModItem(UniversalSingularities.ID, "universal.projectRed.singularity", 1, 0, missing),
                'V',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 0, missing),
                'W',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 1, missing),
                'X',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 12, missing),
                'Y',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 6, missing),
                'Z',
                getModItem(Avaritia.ID, "Singularity", 1, 9, missing),
                '0',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 15, missing),
                '1',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 2, missing),
                '2',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 0, missing),
                '3',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 3, missing),
                '4',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                '5',
                getModItem(UniversalSingularities.ID, "universal.draconicEvolution.singularity", 1, 0, missing),
                '6',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 7, missing),
                '7',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 30, missing),
                '8',
                getModItem(UniversalSingularities.ID, "universal.draconicEvolution.singularity", 1, 1, missing),
                '9',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 3, missing),
                'a',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 6, missing),
                'b',
                getModItem(EternalSingularity.ID, "eternal_singularity", 1, 0, missing),
                'c',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 4, missing),
                'd',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 8, missing),
                'e',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 23, missing),
                'f',
                getModItem(Avaritia.ID, "Singularity", 1, 5, missing),
                'g',
                getModItem(Avaritia.ID, "Singularity", 1, 2, missing),
                'h',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 22, missing),
                'i',
                getModItem(ScienceNotLeisure.ID, "StargateTier4", 1, 0, missing),
                'j',
                getModItem(Avaritia.ID, "Singularity", 1, 7, missing),
                'k',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 14, missing),
                'l',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 19, missing),
                'm',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 6, missing),
                'n',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 10, missing),
                'o',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 6, missing),
                'p',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 3, missing),
                'q',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 24, missing),
                'r',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 25, missing),
                's',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 15, missing),
                't',
                getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1, 1, missing),
                'u',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 26, missing),
                'v',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 2, missing),
                'w',
                getModItem(Avaritia.ID, "Singularity", 1, 11, missing),
                'x',
                getModItem(Avaritia.ID, "Singularity", 1, 6, missing),
                'y',
                getModItem(Avaritia.ID, "Singularity", 1, 10, missing),
                'z',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 21, missing),
                '/',
                getModItem(UniversalSingularities.ID, "universal.tinkersConstruct.singularity", 1, 4, missing),
                '<',
                getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1, 2, missing),
                '>',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 4, missing),
                ';',
                getModItem(EternalSingularity.ID, "combined_singularity", 1, 1, missing),
                ':',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 5, missing),
                '[',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 9, missing),
                ']',
                getModItem(Avaritia.ID, "Singularity", 1, 3, missing),
                '^',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 27, missing),
                '_',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 28, missing),
                '=',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 29, missing),
                '?',
                getModItem(UniversalSingularities.ID, "universal.vanilla.singularity", 1, 0, missing),
                '~',
                getModItem(UniversalSingularities.ID, "universal.enderIO.singularity", 1, 3, missing),
                '!',
                getModItem(UniversalSingularities.ID, "universal.general.singularity", 1, 13, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier6", 1, 0, missing),
                "AAAAAAAAA",
                "BCDEFGHIJ",
                "KLMNMNMOP",
                "QRNSTUNVW",
                "XYMZ01M23",
                "45N678N9a",
                "bcMNdNMef",
                "ghijklmno",
                "ppppppppp",
                'A',
                createItemStack(
                    EnderIO.ID,
                    "blockCapBank",
                    1,
                    0,
                    "{type:\"CREATIVE\",storedEnergyRF:2500000}",
                    missing),
                'B',
                getModItem(OpenComputers.ID, "item", 1, 114, missing),
                'C',
                getModItem(KubaTech.ID, "kubaitems", 1, 41, missing),
                'D',
                getModItem(DraconicEvolution.ID, "dezilsMarshmallow", 1, 0, missing),
                'E',
                getModItem(GalacticraftAmunRa.ID, "item.schematic", 1, 0, missing),
                'F',
                getModItem(DraconicEvolution.ID, "teleporterMKII", 1, 0, missing),
                'G',
                getModItem(GalacticraftCore.ID, "item.schematic", 1, 1, missing),
                'H',
                getModItem(DraconicEvolution.ID, "chaoticCore", 1, 0, missing),
                'I',
                getModItem(KubaTech.ID, "kubaitems", 1, 39, missing),
                'J',
                getModItem(StevesCarts2.ID, "CartModule", 1, 61, missing),
                'K',
                getModItem(OpenComputers.ID, "item", 1, 91, missing),
                'L',
                getModItem(ThaumicEnergistics.ID, "storage.essentia", 1, 4, missing),
                'M',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                'N',
                getModItem(SGCraft.ID, "stargateRing", 1, 0, missing),
                'O',
                createItemStack(Botania.ID, "manaTablet", 1, 0, "{mana:500000,creative:1b}", missing),
                'P',
                getModItem(StevesCarts2.ID, "upgrade", 1, 14, missing),
                'Q',
                getModItem(OpenComputers.ID, "item", 1, 93, missing),
                'R',
                getModItem(GalaxySpace.ID, "item.SchematicTier8", 1, 0, missing),
                'S',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 4, missing),
                'T',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32417, missing),
                'U',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 5, missing),
                'V',
                getModItem(GalacticraftMars.ID, "item.schematic", 1, 0, missing),
                'W',
                getModItem(GalacticraftCore.ID, "item.infiniteOxygen", 1, 0, missing),
                'X',
                getModItem(OpenComputers.ID, "item", 1, 90, missing),
                'Y',
                getModItem(Thaumcraft.ID, "ItemEldritchObject", 1, 3, missing),
                'Z',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 2, missing),
                '0',
                getModItem(ExtraUtilities.ID, "dark_portal", 1, 0, missing),
                '1',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 3, missing),
                '2',
                getModItem(Botania.ID, "pool", 1, 1, missing),
                '3',
                getModItem(ProjectRedFabrication.ID, "projectred.fabrication.icchip", 1, 1, missing),
                '4',
                getModItem(OpenComputers.ID, "item", 1, 103, missing),
                '5',
                getModItem(GalaxySpace.ID, "item.SchematicTier7", 1, 0, missing),
                '6',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 0, missing),
                '7',
                getModItem(GregTech.ID, "gt.comb", 1, 119, missing),
                '8',
                getModItem(ElectroMagicTools.ID, "EssentiaGenerators", 1, 1, missing),
                '9',
                getModItem(GalaxySpace.ID, "item.SchematicTier4", 1, 0, missing),
                'a',
                getModItem(AE2WCT.ID, "infinityBoosterCard", 1, 0, missing),
                'b',
                getModItem(OpenComputers.ID, "item", 1, 69, missing),
                'c',
                getModItem(Witchery.ID, "ingredient", 1, 96, missing),
                'd',
                getModItem(ScienceNotLeisure.ID, "StargateTier5", 1, 0, missing),
                'e',
                createItemStack(Botania.ID, "specialFlower", 1, 0, "{type:\"asgardandelion\"}", missing),
                'f',
                getModItem(AppliedEnergistics2.ID, "tile.BlockSingularityCraftingStorage", 1, 0, missing),
                'g',
                getModItem(Computronics.ID, "computronics.ocSpecialParts", 1, 0, missing),
                'h',
                getModItem(KubaTech.ID, "kubaitems", 1, 38, missing),
                'i',
                getModItem(Avaritia.ID, "Infinity_Pickaxe", 1, 0, missing),
                'j',
                getModItem(GalaxySpace.ID, "item.SchematicTier6", 1, 0, missing),
                'k',
                getModItem(Botania.ID, "terraPick", 1, 0, missing),
                'l',
                getModItem(GalaxySpace.ID, "item.SchematicTier5", 1, 0, missing),
                'm',
                getModItem(ThaumicTinkerer.ID, "ichorPickGem", 1, 0, missing),
                'n',
                getModItem(KubaTech.ID, "kubaitems", 1, 40, missing),
                'o',
                getModItem(Witchery.ID, "infinityegg", 1, 0, missing),
                'p',
                getModItem(DraconicEvolution.ID, "reactorCore", 1, 0, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier7", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "STUVWXYZ0",
                "123444567",
                "89a4b4cde",
                "fgh4i4jkl",
                "mnopqrstu",
                "vwxyz(){}",
                "[];:/#%^*",
                'A',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32700, missing),
                'B',
                getModItem(IndustrialCraft2.ID, "itemPartCircuit", 1, 0, missing),
                'C',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32702, missing),
                'D',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32701, missing),
                'E',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32709, missing),
                'F',
                getModItem(IndustrialCraft2.ID, "itemPartCircuitAdv", 1, 0, missing),
                'G',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32080, missing),
                'H',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32703, missing),
                'I',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32704, missing),
                'J',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32155, missing),
                'K',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32156, missing),
                'L',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32157, missing),
                'M',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32166, missing),
                'N',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32167, missing),
                'O',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32168, missing),
                'P',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32169, missing),
                'Q',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32170, missing),
                'R',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32705, missing),
                'S',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32154, missing),
                'T',
                GTNLItemList.CircuitResonaticZPM.get(1),
                'U',
                GTNLItemList.CircuitResonaticUV.get(1),
                'V',
                GTNLItemList.CircuitResonaticUHV.get(1),
                'W',
                GTNLItemList.CircuitResonaticUEV.get(1),
                'X',
                GTNLItemList.CircuitResonaticUIV.get(1),
                'Y',
                getModItem(NewHorizonsCoreMod.ID, "item.HighEnergyFlowCircuit", 1, 0, missing),
                'Z',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32171, missing),
                '0',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32082, missing),
                '1',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32120, missing),
                '2',
                GTNLItemList.CircuitResonaticLuV.get(1),
                '3',
                getModItem(NewHorizonsCoreMod.ID, "item.EngravedQuantumChip", 1, 0, missing),
                '4',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                '5',
                getModItem(NewHorizonsCoreMod.ID, "item.NanoCircuit", 1, 0, missing),
                '6',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32172, missing),
                '7',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32083, missing),
                '8',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32099, missing),
                '9',
                GTNLItemList.CircuitResonaticIV.get(1),
                'a',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32668, missing),
                'b',
                getModItem(GregTech.ID, "gt.integrated_circuit", 1, 0, missing),
                'c',
                getModItem(NewHorizonsCoreMod.ID, "item.PikoCircuit", 1, 0, missing),
                'd',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32173, missing),
                'e',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32084, missing),
                'f',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32098, missing),
                'g',
                GTNLItemList.CircuitResonaticEV.get(1),
                'h',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32068, missing),
                'i',
                getModItem(ScienceNotLeisure.ID, "StargateTier6", 1, 0, missing),
                'j',
                getModItem(NewHorizonsCoreMod.ID, "item.QuantumCircuit", 1, 0, missing),
                'k',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32174, missing),
                'l',
                getModItem(GregTech.ID, "gt.metaitem.01", 1, 32706, missing),
                'm',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32097, missing),
                'n',
                GTNLItemList.CircuitResonaticHV.get(1),
                'o',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32070, missing),
                'p',
                getModItem(NewHorizonsCoreMod.ID, "item.EngineeringProcessorSpatialPulsatingCore", 1, 0, missing),
                'q',
                getModItem(NewHorizonsCoreMod.ID, "item.EngineeringProcessorEssentiaPulsatingCore", 1, 0, missing),
                'r',
                getModItem(NewHorizonsCoreMod.ID, "item.EngineeringProcessorFluidEmeraldCore", 1, 0, missing),
                's',
                getModItem(NewHorizonsCoreMod.ID, "item.EngineeringProcessorItemAdvEmeraldCore", 1, 0, missing),
                't',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32175, missing),
                'u',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32085, missing),
                'v',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32095, missing),
                'w',
                GTNLItemList.CircuitResonaticMV.get(1),
                'x',
                GTNLItemList.CircuitResonaticLV.get(1),
                'y',
                GTNLItemList.CircuitResonaticULV.get(1),
                'z',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32078, missing),
                '(',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32075, missing),
                ')',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32177, missing),
                '{',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32176, missing),
                '}',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32086, missing),
                '[',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32094, missing),
                ']',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32093, missing),
                ';',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32092, missing),
                ':',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32091, missing),
                '/',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32090, missing),
                '#',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32096, missing),
                '%',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32089, missing),
                '^',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32088, missing),
                '*',
                getModItem(GregTech.ID, "gt.metaitem.03", 1, 32087, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier8", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "STUVWXYZ0",
                "123444567",
                "89a4b4cde",
                "fgh4i4jkl",
                "mnopqrstu",
                "vwxyz/<>;",
                ":[]^_=?~!",
                'A',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14003, missing),
                'B',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14006, missing),
                'C',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14009, missing),
                'D',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14014, missing),
                'E',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14012, missing),
                'F',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14013, missing),
                'G',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15350, missing),
                'H',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15313, missing),
                'I',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15311, missing),
                'J',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15310, missing),
                'K',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15300, missing),
                'L',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13115, missing),
                'M',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12600, missing),
                'N',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31151, missing),
                'O',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 749, missing),
                'P',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32025, missing),
                'Q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12698, missing),
                'R',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31085, missing),
                'S',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32019, missing),
                'T',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32020, missing),
                'U',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32021, missing),
                'V',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32022, missing),
                'W',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32023, missing),
                'X',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13106, missing),
                'Y',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 687, missing),
                'Z',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3010, missing),
                '0',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13367, missing),
                '1',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12733, missing),
                '2',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12732, missing),
                '3',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31072, missing),
                '4',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                '5',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31073, missing),
                '6',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31021, missing),
                '7',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12712, missing),
                '8',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 863, missing),
                '9',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14002, missing),
                'a',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 828, missing),
                'b',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31027, missing),
                'c',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10501, missing),
                'd',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32013, missing),
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12738, missing),
                'f',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15411, missing),
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 751, missing),
                'h',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13001, missing),
                'i',
                getModItem(ScienceNotLeisure.ID, "StargateTier7", 1, 0, missing),
                'j',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1132, missing),
                'k',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12792, missing),
                'l',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15312, missing),
                'm',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15314, missing),
                'n',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32018, missing),
                'o',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 360, missing),
                'p',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 865, missing),
                'q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 686, missing),
                'r',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12734, missing),
                's',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12735, missing),
                't',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14201, missing),
                'u',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13532, missing),
                'v',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12730, missing),
                'w',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12729, missing),
                'x',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31075, missing),
                'y',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13104, missing),
                'z',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 829, missing),
                '/',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13366, missing),
                '<',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32014, missing),
                '>',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31035, missing),
                ';',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 17000, missing),
                ':',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14202, missing),
                '[',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31041, missing),
                ']',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31084, missing),
                '^',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31083, missing),
                '_',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31082, missing),
                '=',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31080, missing),
                '?',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31078, missing),
                '~',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 998, missing),
                '!',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 790, missing));

        ExtremeCraftingManager.getInstance()
            .addExtremeShapedOreRecipe(
                getModItem(ScienceNotLeisure.ID, "StargateTier9", 1, 0, missing),
                "ABCDEFGHI",
                "JKLMNOPQR",
                "STUVWXYZ0",
                "123444567",
                "89a4b4cde",
                "fgh4i4jkl",
                "mnopqrstu",
                "vwxyz/<>;",
                ":[]^_=?~!",
                'A',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12791, missing),
                'B',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 797, missing),
                'C',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31026, missing),
                'D',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 792, missing),
                'E',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 144, missing),
                'F',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32001, missing),
                'G',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 9400, missing),
                'H',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 866, missing),
                'I',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 2730, missing),
                'J',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 836, missing),
                'K',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 997, missing),
                'L',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 963, missing),
                'M',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1023, missing),
                'N',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32017, missing),
                'O',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 13102, missing),
                'P',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10505, missing),
                'Q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10508, missing),
                'R',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10500, missing),
                'S',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 850, missing),
                'T',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 356, missing),
                'U',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 910, missing),
                'V',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12731, missing),
                'W',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 875, missing),
                'X',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31077, missing),
                'Y',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 791, missing),
                'Z',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31074, missing),
                '0',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 12022, missing),
                '1',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 14001, missing),
                '2',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15410, missing),
                '3',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 996, missing),
                '4',
                getModItem(SGCraft.ID, "stargateBase", 1, 0, missing),
                '5',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 16999, missing),
                '6',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3008, missing),
                '7',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 799, missing),
                '8',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15497, missing),
                '9',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15510, missing),
                'a',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3004, missing),
                'b',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31028, missing),
                'c',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31076, missing),
                'd',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32027, missing),
                'e',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 357, missing),
                'f',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 5001, missing),
                'g',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1130, missing),
                'h',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1172, missing),
                'i',
                getModItem(ScienceNotLeisure.ID, "StargateTier8", 1, 0, missing),
                'j',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 124, missing),
                'k',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 129, missing),
                'l',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31069, missing),
                'm',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 358, missing),
                'n',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 992, missing),
                'o',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 347, missing),
                'p',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 15506, missing),
                'q',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 849, missing),
                'r',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31065, missing),
                's',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31050, missing),
                't',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 995, missing),
                'u',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 862, missing),
                'v',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 811, missing),
                'w',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 1159, missing),
                'x',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 140, missing),
                'y',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 796, missing),
                'z',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 798, missing),
                '/',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 148, missing),
                '<',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10507, missing),
                '>',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 10506, missing),
                ';',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 32026, missing),
                ':',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31150, missing),
                '[',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 835, missing),
                ']',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 366, missing),
                '^',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 31023, missing),
                '_',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 859, missing),
                '=',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 942, missing),
                '?',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 3011, missing),
                '~',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 812, missing),
                '!',
                getModItem(GregTech.ID, "gt.blockmachines", 1, 840, missing));
    }
}
