package com.science.gtnl.common.materials;

import java.util.Collections;

import gregtech.api.enums.Dyes;
import gregtech.api.enums.Materials;
import gregtech.api.enums.TCAspects;
import gregtech.api.enums.TextureSet;
import gregtech.api.enums.TierEU;

public class GTMaterial {

    public static void load() {
        Materials BlueDog = new Materials(
            170,
            new TextureSet("BLUE_DOG", true),
            1.0F,
            8 * 2621440,
            31,
            1 | 2 | 64 | 128,
            255,
            255,
            255,
            0,
            "BlueDog",
            "Blue Dog",
            -1,
            -1,
            0,
            14000,
            true,
            false,
            2,
            1,
            1,
            Dyes._NULL,
            Collections.singletonList(new TCAspects.TC_AspectStack(TCAspects.AQUA, 1)))
                .disableAutoGeneratedBlastFurnaceRecipes()
                .disableAutoGeneratedVacuumFreezerRecipe()
                .setProcessingMaterialTierEU(TierEU.RECIPE_UMV);
    }
}
